baseURL = 'https://shuosc.github.io/fly'
title = 'SHUFly - 上海大学溯源手册'
theme = 'FixIt'
canonifyURLs = true  # Fix GitHub Pages wrong path

# [en, zh-cn, fr, ...] 设置默认的语言
defaultContentLanguage = "zh-cn"
# 网站语言，仅在这里 CN 大写
languageCode = "zh-CN"
# 是否包括中日韩文字
hasCJKLanguage = true




# 设置自动更新修改时间
[frontmatter]
date = [':git', 'lastmod', ':default']
lastmod = [':fileModTime', ':git', 'lastmod', ':default']
[params]
  # FixIt 主题版本
  version = "0.2.X"
  # Header config
  [params.header]
    # FixIt 0.2.13 | CHANGED desktop header mode ("sticky", "normal", "auto")
    desktopMode = "sticky"
    # FixIt 0.2.13 | CHANGED mobile header mode ("sticky", "normal", "auto")
    mobileMode = "auto"
    # FixIt 0.2.0 | NEW Header title config
    [params.header.title]
      # URL of the LOGO
      logo = "/shugug.webp"
      # title name
      name = "SHUFly"

# 中文主页信息设置
[languages.zh-cn.params.home]
  # RSS 文章数目
  rss = 10
  # 主页个人信息
  [languages.zh-cn.params.home.profile]
    enable = true
    # Gravatar 邮箱，用于优先在主页显示的头像
    gravatarEmail = ""
    # 主页显示头像的 URL
    avatarURL = "/shufly.webp"
    # 主页显示的网站标题 (支持 HTML 格式)
    title = "上海大学溯源手册"
    # 是否为副标题显示打字机动画
    typeit = true
    # 是否显示社交账号
    social = false
    # 免责声明 (支持 HTML 格式)
    disclaimer = ""
  # 主页文章列表
  [languages.zh-cn.params.home.posts]
    enable = true
    # 主页每页显示文章数量
    paginate = 8

# 中文菜单配置
[languages.zh-cn.menu]
  [[languages.zh-cn.menu.main]]
    identifier = "posts"
    # 父级菜单项的标识符 (identifier) since v0.2.14
    parent = ""
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = "<i class='fa-solid fa-archive fa-fw fa-sm'></i>"
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    name = "所有文章"
    url = "/posts/"
    title = ""
    weight = 1
  [[languages.zh-cn.menu.main]]
    identifier = "categories"
    pre = "<i class='fa-solid fa-th fa-fw fa-sm'></i>"
    post = ""
    name = "分类"
    url = "/categories/"
    title = ""
    weight = 2
  [[languages.zh-cn.menu.main]]
    identifier = "tags"
    pre = "<i class='fa-solid fa-tags fa-fw fa-sm'></i>"
    post = ""
    name = "标签"
    url = "/tags/"
    title = ""
    weight = 3
  [[languages.zh-cn.menu.main]]
    identifier = "friends"
    pre = "<i class='fa-solid fa-users fa-fw fa-sm'></i>"
    post = ""
    name = "友链"
    url = "/friends/"
    title = "友情链接"
    weight = 4
  [[languages.zh-cn.menu.main]]
    identifier = "about"
    pre = "<i class='fa-solid fa-info-circle fa-fw fa-sm'></i>"
    post = ""
    name = "关于"
    url = "/about/"
    title = ""
    weight = 5
  [[languages.zh-cn.menu.main]]
    identifier = "github"
    pre = "<i class='fa-brands fa-github fa-fw'></i>"
    post = ""
    name = ""
    url = "https://github.com/shuosc/fly"
    title = "GitHub"
    weight = 6


# Hugo 解析文档的配置
[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false 是必要的设置
    # (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  # Goldmark 是 Hugo 0.60 以来的默认 Markdown 解析库
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # 是否在文档中直接使用 HTML 标签
      unsafe = true
  # 目录设置
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6


